### PR TITLE
Add new summit speakers

### PR DESCRIPTION
**Pull request by Holben888**

### CODE REVIEW

**Comment by nikhilro** [comment]
Mild preference to reorder. Thinking Kathy Pham instead of Tim Salau would be better for the first place.

Also, did the carousel always move so slowly? It's probably fine.

**Comment by Holben888** [comment]
Hm, yeah I didn't adjust it myself. Totally agree they should scroll faster though, since we have so many more speakers this time. Tweaked it in the JS!

**Comment by nikhilro** [comment]
nice, thanks, ship it 🚢

**Comment by nikhilro** [comment]
WAIT, peter singer should def be in first 3. Tim Salau can move to 4th or 5th. Then ship it

**Pull request merged**
